### ISSUE TITLE
Package 'imu_driver' not found: "package 'imu_driver' not found, searching: ['/opt/ros/humble']"

### ISSUE THREAD

**Issue by Narek-939** [1222-takeshi/ros2-mpu6050-driver#7]
Please tell me, how i can fix it??

**Comment by 1222-takeshi** [comment]
Could you tell me about any works you have conducted?

Have you implemented the following process?
```
mkdir -p ros2_ws/src
cd ros2_ws/src
git clone https://github.com/1222-takeshi/ros2-mpu6050-driver.git
cd ..
rosdep install --from-paths src -iry --rosdistro $ROS_DISTRO
colcon build --symlink-install
source install/setup.bash
```

**Comment by 1222-takeshi** [comment]
@Narek-939

**Comment by Narek-939** [comment]
Hello, yes I have done it, but encountered to this error 



CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/arm-none-eabi-g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/vis/Desktop/ros2-mpu6050-driver/build/imu_driver/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_ea481/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_ea481.dir/build.make CMakeFiles/cmTC_ea481.dir/build
    gmake[1]: Entering directory '/home/vis/Desktop/ros2-mpu6050-driver/build/imu_driver/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_ea481.dir/testCXXCompiler.cxx.o
    /usr/bin/arm-none-eabi-g++    -o CMakeFiles/cmTC_ea481.dir/testCXXCompiler.cxx.o -c /home/vis/Desktop/ros2-mpu6050-driver/build/imu_driver/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_ea481
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ea481.dir/link.txt --verbose=1
    /usr/bin/arm-none-eabi-g++ CMakeFiles/cmTC_ea481.dir/testCXXCompiler.cxx.o -o cmTC_ea481 
    /usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: /usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
    /build/newlib-pB30de/newlib-3.3.0/build/arm-none-eabi/newlib/libc/stdlib/../../../../../newlib/libc/stdlib/exit.c:64: undefined reference to `_exit'
    collect2: error: ld returned 1 exit status
    gmake[1]: *** [CMakeFiles/cmTC_ea481.dir/build.make:99: cmTC_ea481] Error 1
    gmake[1]: Leaving directory '/home/vis/Desktop/ros2-mpu6050-driver/build/imu_driver/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_ea481/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

**Comment by Narek-939** [comment]
I updated my arm-none-eabi-g++, but that way dont work

**Comment by 1222-takeshi** [comment]
Hmm ... :thinking: 
I will check my raspberry-Pi 4 (Ubuntu22.04 / Ros2 Humble).

**Comment by 1222-takeshi** [comment]
I tried to build the imu_driver and it was successful. I used the following commands.

```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-w" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache --packages-select imu_driver
```

The outputs were as follows:
```
Starting >>> imu_driver
[Processing: imu_driver]                             
Finished <<< imu_driver [47.4s]                       

Summary: 1 package finished [48.6s]
```
"If the following command doesn't produce any output, you can use the command "source /opt/ros/humble/setup.bash".

Please execute: 
```
echo $ROS_DISTRO
```
